### ISSUE TITLE
I want the site to inform me what safeguarding is and how I can help someone I'm concerned about.

### ISSUE THREAD

**Issue by Gracey46** [Gracey46/Safeguarding#2]
I want the website to contain information that helps identify what safeguarding is, what are the signs and actions I can take.

**Assessment Criteria**
Make sure that on the page there is the following information:

- What safeguarding is.
- What are the signs of someone who maybe at risk
- What actions can be taken to protect anyone.

**Tasks**

- [x] Create cards in HTML displaying information for each of the points.
- [x] Arrange the cards clearly on the page using CSS and bootstrap
- [x] Make sure all information is in a readable font, clear on colored backgrounds and good size.
