### ISSUE TITLE
I want to be able to find more information if I want to read more

### ISSUE THREAD

**Issue by Gracey46** [Gracey46/Safeguarding#3]
I want the website to have links to other pages that are useful if I have more questions or want to know more. 

**Assessment Criteria**
Make sure there is a section of workable links to other websites that are content-relevant.

**Tasks**

- [x] Make sure there is a section of links to other sites.
- [x] Make sure all links work using HTML.
- [x] Present the links clearly and make sure they can be clicked on and they will take the user to the correct website in a new tab.
