### ISSUE TITLE
I want to be able to contact someone

### ISSUE THREAD

**Issue by Gracey46** [Gracey46/Safeguarding#4]
I want to be able to contact someone on the site if I have any worries, need more information or guidance. 

**Assessment Criteria**
The site needs to have a working contact form for the users to fill in. The form should have the users name, email and space for a comment. The email and comment must be required. 

**Tasks**

- [ ] Using HTML /bootstrap make a form with name, email, and comment sections. 
- [ ] Make sure the email and comment is required information.
- [ ] Have working buttons.
